export default {
	isEmpty: true,
	isBusy: false,
	isServerError: false,
	isEndReached: false,
	isChatPossible: true,
	isCartOpen: false,
	isFavoritesModalOpen: false,
	isCartReady: false,
	filterSettings: {
		isTourDone: false,
		isOpen: false,
	},
	homepageScroll: 0,
	productfilters: [],
	productsorters: [],
	products: [],
	currentProduct: {},
	currentSort: '',
	userInfo: {
		name: '',
		contact: '',
		email: '',
		phone: '',
		vatNumber: '',
		shippingMethod: null,
		shippingAddress: {
			street: '',
			postalCode: '',
			city: '',
			countryCode: '',
		},
		billingAddress: {
			street: '',
			postalCode: '',
			city: '',
			countryCode: '',
		},
		cartProducts: [],
		lastOrderedProducts: [],
		recentProducts: [],
		favoriteProducts: [],
		favoritesOptions: [],
		rugSize: {
			length: 305,
			width: 245,
			hasUpdated: false,
		},
		sentFavorites: [],
		hasReactedToPopup: false,
	},
	sidebar: {
		activeTab: 'recent',
		isOpen: false,
	},
};
